server:
  port: 8095
  servlet:
    context-path: "/"
management:
  server:
    port: 8096
    servlet:
      context-path: "/profile-management"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: heapdump, threaddump
  info:
    git:
      mode: full

logging:
  level:
    root: info
  file:
    name: "target/profile-management"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  logURL: log:%s?level=INFO&showExchangeId=true&showHeaders=true

spring:
  application:
    name: profile-management-adapter
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:ayodb
    username: user_ayo
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

ayo:
  http:
    timeout: 30000
  properties:
    server: http://localhost:8095
    mtnServerUrl: /ayo/mtn/profile-service/v1
  public-key-path: 'classpath:dev/ayo-dev-public.pem'
  jwt:
    issuer: "ayo"
    key-identifier: "ayo.1"
    signing-algorithm: "RS256"
    type: "JWT"
    expiry-time-in-seconds: 86400
    private-key-path: 'classpath:dev/ayo-dev-private.pem'
    security:
      filter:
        bypass: true
  ssl:
    keystore: clientKeyStore.jks
    keystore-password: chaasdRJFsdcjrmd
    truststore: ayo_dev_TrustStore.jks
    truststore-password: password
    keysPath:  /opt/ayoworkingdirectory/keys

